version: "3.8"
services:
  python_model:
    build: ./python_model
    container_name: python_model
    restart: unless-stopped
    volumes:
      - ./models:/app/models:ro
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1

  node_backend:
    build: ./node_backend
    container_name: node_backend
    restart: unless-stopped
    depends_on:
      - python_model
    ports:
      - "3000:3000"
    environment:
      - MODEL_SERVICE_URL=http://python_model:5000/predict

  frontend:
    build: ./frontend
    container_name: food_frontend
    restart: unless-stopped
    depends_on:
      - node_backend
    ports:
      - "5173:5173"
